### PR TITLE
Release 4.1.1

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by highb** [comment]
@bastelfreak @ekohl Hi, did something strange happen when you pushed this gem up to Rubygems yesterday? I'm getting a checksum mismatch when attempting to download this version:
```
# puppet-blacksmith not pinned in Gemfile, no gemfile lock
➜  puppetlabs-pe_install git:(hoyt) bundle install --force
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Unable to use the platform-specific (universal-darwin) version of facter (2.5.1) because it has different dependencies from the ruby version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Unable to use the platform-specific (universal-darwin) version of puppet (5.3.2) because it has different dependencies from the ruby version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Installing rake 12.1.0
Installing public_suffix 3.0.0
Using bundler 1.15.4
Installing safe_yaml 1.0.4
Installing diff-lcs 1.3
Installing unf_ext 0.0.7.4 with native extensions
Installing facter 2.5.1
Installing jgrep 1.5.0
Installing fast_gettext 1.1.0
Installing locale 2.1.2
Installing text 1.3.1
Installing hashdiff 0.3.6
Installing hiera 3.4.2
Installing hocon 1.2.5
Installing json 2.1.0 with native extensions
Installing stomp 1.4.4
Installing systemu 2.6.5
Installing metaclass 0.0.4
Installing spdx-licenses 1.1.0
Installing mime-types-data 3.2016.0521
Installing netrc 0.11.0
Installing parallel 1.12.0
Installing puppet-lint 2.3.0
Installing rspec-support 3.6.0
Installing vagrant-wrapper 2.0.3
Installing puppet-syntax 2.4.1
Installing addressable 2.5.2
Installing crack 0.4.3
Installing unf 0.1.4
Installing facterdb 0.3.12
Installing gettext 3.2.4
Installing mcollective-client 2.11.2
Installing mocha 1.3.0
Installing mime-types 3.1
Installing parallel_tests 2.16.0
Installing rspec-core 3.6.0
Installing rspec-expectations 3.6.0
Installing rspec-mocks 3.6.0
Installing json-schema 2.8.0
Installing webmock 3.0.1
Installing domain_name 0.5.20170404
Installing gettext-setup 0.28
Installing rspec 3.6.0
Installing metadata-json-lint 2.0.2
Installing http-cookie 1.0.3
Installing puppet 5.3.2
Installing rspec-puppet 2.6.9
Installing rest-client 2.0.2
Installing rspec-puppet-facts 1.8.0
Installing puppetlabs_spec_helper 2.3.2
Fetching puppet-blacksmith 4.1.1
Installing puppet-blacksmith 4.1.1
Bundler cannot continue installing puppet-blacksmith (4.1.1).
The checksum for the downloaded `puppet-blacksmith-4.1.1.gem` does not match the checksum given by the server. This means the contents of the downloaded gem
is different from what was uploaded to the server, and could be a potential security issue.

To resolve this issue:
1. delete the downloaded gem located at: `/Users/highb/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/puppet-blacksmith-4.1.1/puppet-blacksmith-4.1.1.gem`
2. run `bundle install`

If you wish to continue installing the downloaded gem, and are certain it does not pose a security issue despite the mismatching checksum, do the following:
1. run `bundle config disable_checksum_validation true` to turn off checksum verification
2. run `bundle install`

(More info: The expected SHA256 checksum was "7bec2418a4d85ccb747b4614ad2002697d39af7fc3126a3c5eb950498f0b4bc8", but the checksum for the downloaded gem was
"754eaf5edbcb3956064a14719c937ac6df84baceb5e2b39d0e4833dbca1c85b4".)

# Then I pin to 4.1.0 in the Gemfile...
➜  puppetlabs-pe_install git:(hoyt) bundle install --force
The latest bundler is 1.16.0.pre.3, but you are currently running 1.15.4.
To update, run `gem install bundler --pre`
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Unable to use the platform-specific (universal-darwin) version of facter (2.5.1) because it has different dependencies from the ruby version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Unable to use the platform-specific (universal-darwin) version of puppet (5.3.2) because it has different dependencies from the ruby version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Installing rake 12.1.0
Installing public_suffix 3.0.0
Using bundler 1.15.4
Installing safe_yaml 1.0.4
Installing diff-lcs 1.3
Installing unf_ext 0.0.7.4 with native extensions
Installing facter 2.5.1
Installing jgrep 1.5.0
Installing fast_gettext 1.1.0
Installing locale 2.1.2
Installing text 1.3.1
Installing hashdiff 0.3.6
Installing hiera 3.4.2
Installing hocon 1.2.5
Installing json 2.1.0 with native extensions
Installing stomp 1.4.4
Installing systemu 2.6.5
Installing metaclass 0.0.4
Installing spdx-licenses 1.1.0
Installing mime-types-data 3.2016.0521
Installing netrc 0.11.0
Installing parallel 1.12.0
Installing puppet-lint 2.3.0
Installing rspec-support 3.6.0
Installing vagrant-wrapper 2.0.3
Installing puppet-syntax 2.4.1
Installing addressable 2.5.2
Installing crack 0.4.3
Installing unf 0.1.4
Installing facterdb 0.3.12
Installing gettext 3.2.4
Installing mcollective-client 2.11.2
Installing mocha 1.3.0
Installing mime-types 3.1
Installing parallel_tests 2.16.0
Installing rspec-core 3.6.0
Installing rspec-expectations 3.6.0
Installing rspec-mocks 3.6.0
Installing json-schema 2.8.0
Installing webmock 3.0.1
Installing domain_name 0.5.20170404
Installing gettext-setup 0.28
Installing rspec 3.6.0
Installing metadata-json-lint 2.0.2
Installing http-cookie 1.0.3
Installing puppet 5.3.2
Installing rspec-puppet 2.6.9
Installing rest-client 2.0.2
Installing rspec-puppet-facts 1.8.0
Installing puppetlabs_spec_helper 2.3.2
Fetching puppet-blacksmith 4.1.0
Installing puppet-blacksmith 4.1.0
Bundle complete! 12 Gemfile dependencies, 51 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from metadata-json-lint:

  ----------------------------------------------------------
      For the most accurate results, the semantic_puppet
      gem should be included within your Gemfile if you
      use Puppet <= 4.8.x
  ----------------------------------------------------------
  %
```

**Comment by highb** [comment]
I also tried updating bundler to 1.16.0, which does not seem to help.

**Comment by ekohl** [comment]
That's odd because I'm able to install it using bundler but also:

```
$ wget https://rubygems.org/downloads/puppet-blacksmith-4.1.1.gem > /dev/null
$ sha256sum puppet-blacksmith-4.1.1.gem 
754eaf5edbcb3956064a14719c937ac6df84baceb5e2b39d0e4833dbca1c85b4  puppet-blacksmith-4.1.1.gem
```

That doesn't match ```7bec2418a4d85ccb747b4614ad2002697d39af7fc3126a3c5eb950498f0b4bc8``` as would be expected.

It does appear that all 4 jobs attempt to push the gem to rubygems (https://travis-ci.org/voxpupuli/puppet-blacksmith/builds/316635123) so possibly there's a problem there. I'll do a 4.1.2 release.

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-blacksmith/pull/61

**Pull request merged**
