### PR TITLE
Allow loading forge credentials from project dir

### PR DESCRIPTION
**Pull request by felixb**
We now search the .puppetforge.yml in current working dir first.
Fallback to home dir if not found.

### CODE REVIEW

**Comment by jyaworski** [comment]
Hello:

What does this gain us? I'm not entirely understanding.

**Comment by felixb** [comment]
We are running a local forge for internal puppet modules. This creates the need of pushing modules to different forge servers with different credentials.

This change allows us to check in a `.puppetforge.yml` for ouor local modules and have jenkins push it automatically to the local forge server.

**Comment by jyaworski** [comment]
@felixb can you rebase?

**Comment by felixb** [comment]
done.

**Pull request merged**
